---
# Create Docker network role

- name: Create Docker network
  docker_network:
    name: "{{ docker_network }}"
    state: present
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
