---
# Launch application role

- name: Run Simple API application
  docker_container:
    name: simple-api
    image: nikanika14/tp-devops-simple-api:latest
    pull: true
    recreate: true
    state: started
    restart_policy: always
    networks:
      - name: my-network
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
