---
# Launch frontend role

- name: Run Frontend container
  docker_container:
    name: frontend
    image: "{{ dockerhub_username }}/tp-devops-frontend:latest"
    pull: true
    recreate: true
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network }}"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
