---
# Launch database role

- name: Run PostgreSQL database
  docker_container:
    name: database
    image: "{{ dockerhub_username }}/tp-devops-database:latest"
    pull: true
    recreate: true
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network }}"
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - db-volume:/var/lib/postgresql/data
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
